apiVersion: v1
kind: Service
metadata:
  name: vanilla-service
  labels:
    app: vanilla-pod
spec:
  # Type Cluster IP, Load Balancer, Node Port etc.
  # Cluster IP Automatically assigned by Kubernetes
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 9334
    protocol: TCP
  selector:
    app: vanilla-pod
