apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vanilla-ingress
spec:
  ingressClassName: nginx
   # Add TLS 
  rules:
  - host: localhost
    http:
      paths:
      - path: /ms-vanilla
        pathType: Prefix
        backend:
          service:
            # Vanilla Microservice
            name: vanilla-service
            port:
              number: 80

