# Vanilla MicroService Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanilla-deployment
  labels:
    app: vanilla-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      # Matching the labels from Pod MetaData,  Multiple labels can be used
      app: vanilla-pod
  minReadySeconds: 5
  strategy:
    # Re-Create / Rolling Update
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vanilla-pod
        version: "1.0.0"
        release: stable
        organization: Ozazo
    spec:
      containers:
        - name: vanilla-container
          image: arafkarsh/ms-vanilla-service:0.3.4-alpaquita-21-k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9334
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          env:
            - name: JASYPT_ENCRYPTOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vanilla-secret
                  key: JASYPT_ENCRYPTOR
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/application.properties"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: vanilla-configmap-active
                  key: spring.profiles.active
          livenessProbe:
            httpGet:
              path: /ms-vanilla/api/v1/service/live
              port: 9334
          readinessProbe:
            httpGet:
              path: /ms-vanilla/api/v1/service/ready
              port: 9334
          resources:
            limits:
              cpu: 1000m
              memory: 1536Mi
            requests:
              cpu: 1000m
              memory: 1536Mi
      volumes:
        - name: config-volume
          configMap:
            name: vanilla-configmap-prod
