#!/bin/sh
# ============================================================================
# Database Builder
# @author: Araf Karsh Hamid, (c) Copyright 2022-25
# ============================================================================
user='postgres'
port=5433

echo "Connecting to the postgreSQL Server... "
psql -h localhost -p $port -U $user < createdb.sql

