#!/bin/sh
# ============================================================================
# Import Database 
# @author: Araf Karsh Hamid, (c) Copyright 2022-25
# ============================================================================
#psql -h localhost -p 5433 ms_vanilla_334 < ms-sb334.sql
psql -h localhost -p 5433 ms_vanilla_334 < es.sql
