global:
  scrape_interval: 15s  # Default scrape interval for scraping targets.

remote_write:
  - url: "http://localhost:9090/api/v1/write"  # Accept data pushed from OpenTelemetry Collector

scrape_configs:
  - job_name: "prometheus"  # Prometheus itself
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "otel-collector"  # Optional: If you want Prometheus to scrape the OpenTelemetry Collector
    static_configs:
      - targets: ["localhost:8888"]  # Ensure the Collector's Prometheus exporter endpoint is enabled
