apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: vanilla-configmap-default
    files:
      - application.properties

generatorOptions:
  disableNameSuffixHash: true