apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: vanilla-configmap-profiles
    files:
      - application.properties
      - application-dev.properties
      - application-staging.properties
      - application-prod.properties
generatorOptions:
  disableNameSuffixHash: true